version: '3.8'
services:
  mysql:
    image: doananhkiet886/mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=SE_SHOP
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3307:3306'
